# Generated by Django 4.0.6 on 2022-09-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
