# Generated by Django 4.0.6 on 2022-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='messages',
            field=models.ManyToManyField(blank=True, to='message.message'),
        ),
    ]
