# Generated by Django 4.0.6 on 2023-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='gpt',
            field=models.BooleanField(default=False),
        ),
    ]
