# Generated by Django 4.0.6 on 2022-09-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_dm_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
