# Generated by Django 4.0.6 on 2022-09-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dm',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='message.dm'),
        ),
    ]
